qt6: Update OpenSSL to 1.1.1q
This fixes that build error:
ERROR: Conflict in cmake/3.23.1:
    'cmake/3.23.1' requires 'openssl/1.1.1q' while 'qt/6.3.1' requires 'openssl/1.1.1o'.
    To fix this conflict you need to override the package 'openssl' in your root package.